global using ApiCentralPessoa.Models;
global using Microsoft.EntityFrameworkCore;
global using ApiCentralPessoa.Data;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.OpenApi.Models;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using ApiCentralPessoa.Dto;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;